import crypto from "node:crypto"
import { cookies } from "next/headers"

import { appendAdminLog } from "./repo"
import { mutate, readDb } from "./store"
import type { AdminSession, AdminUser, InterviewDriveDb } from "./types"

/**
 * Admin authentication for the interview drive dashboard.
 *
 * Passwords are stored only as scrypt hashes. Sessions are opaque random
 * tokens; the server persists only their SHA-256, so a leaked data file still
 * does not let anyone mint a valid session cookie. Every mutating admin route
 * additionally requires a CSRF token that is bound to the session.
 */

export const SESSION_COOKIE = "rw_id_admin_session"
export const CSRF_HEADER = "x-rw-csrf-token"

const SESSION_TTL_MS = 8 * 60 * 60 * 1000 // 8 hours
const SCRYPT_N = 16_384
const SCRYPT_r = 8
const SCRYPT_p = 1
const SCRYPT_KEYLEN = 64

/* ------------------------------------------------------------- passwords */

/**
 * Encoded as `scrypt:N:r:p:salt:hash`.
 *
 * The separator is ":" rather than the more conventional "$" on purpose:
 * these hashes are pasted into .env, and dotenv expands `$NAME` sequences,
 * which would silently corrupt a $-delimited hash into an unusable value.
 */
export function hashPassword(password: string): string {
  const salt = crypto.randomBytes(16)
  const hash = crypto.scryptSync(password.normalize("NFKC"), salt, SCRYPT_KEYLEN, {
    N: SCRYPT_N,
    r: SCRYPT_r,
    p: SCRYPT_p,
    maxmem: 128 * SCRYPT_N * SCRYPT_r * 2,
  })
  return ["scrypt", SCRYPT_N, SCRYPT_r, SCRYPT_p, salt.toString("base64url"), hash.toString("base64url")].join(":")
}

export function verifyPassword(password: string, stored: string): boolean {
  try {
    // Accept the legacy "$"-delimited form too, so an already-deployed hash
    // keeps working after this change.
    const parts = stored.includes(":") ? stored.split(":") : stored.split("$")
    const [scheme, N, r, p, saltB64, hashB64] = parts
    if (scheme !== "scrypt") return false
    const salt = Buffer.from(saltB64, "base64url")
    const expected = Buffer.from(hashB64, "base64url")
    const actual = crypto.scryptSync(password.normalize("NFKC"), salt, expected.length, {
      N: Number(N),
      r: Number(r),
      p: Number(p),
      maxmem: 128 * Number(N) * Number(r) * 2,
    })
    // Constant-time: never leak how much of the hash matched.
    return crypto.timingSafeEqual(actual, expected)
  } catch {
    return false
  }
}

/* --------------------------------------------------------- admin seeding */

/**
 * Seeds the first admin from the environment.
 *
 * Prefer INTERVIEW_ADMIN_PASSWORD_HASH (generated by scripts/interview-drive-admin.mjs)
 * so no plaintext password ever sits in the environment. INTERVIEW_ADMIN_PASSWORD is
 * accepted as a convenience and is hashed immediately — it is never persisted as-is.
 */
export function seedAdminsFromEnv(db: InterviewDriveDb): boolean {
  const email = (process.env.INTERVIEW_ADMIN_EMAIL || "").trim().toLowerCase()
  const passwordHash = (process.env.INTERVIEW_ADMIN_PASSWORD_HASH || "").trim()
  const plainPassword = process.env.INTERVIEW_ADMIN_PASSWORD || ""
  if (!email || (!passwordHash && !plainPassword)) return false

  const hash = passwordHash || hashPassword(plainPassword)
  const existing = db.admins.find((a) => a.email === email)
  if (existing) {
    const hadStale = db.admins.length > 1
    revokeStaleAdmins(db, email)
    // Let the environment rotate the password without a manual migration.
    if (passwordHash && existing.passwordHash !== passwordHash) {
      existing.passwordHash = passwordHash
      return true
    }
    return hadStale
  }

  const admin: AdminUser = {
    id: crypto.randomUUID(),
    email,
    name: process.env.INTERVIEW_ADMIN_NAME || "Rayon Web Admin",
    passwordHash: hash,
    role: "admin",
    createdAt: new Date().toISOString(),
    lastLoginAt: null,
  }
  db.admins.push(admin)
  revokeStaleAdmins(db, email)
  return true
}

/**
 * Removes any admin account that the environment no longer configures, and
 * kills its sessions.
 *
 * The environment is the single source of truth for who may sign in. Without
 * this, changing INTERVIEW_ADMIN_EMAIL would leave the previous account — and
 * its password — working indefinitely on an already-deployed instance.
 */
function revokeStaleAdmins(db: InterviewDriveDb, keepEmail: string): void {
  const stale = db.admins.filter((a) => a.email !== keepEmail)
  if (stale.length === 0) return

  const staleIds = new Set(stale.map((a) => a.id))
  db.admins = db.admins.filter((a) => a.email === keepEmail)
  db.sessions = db.sessions.filter((session) => !staleIds.has(session.adminId))
  for (const account of stale) {
    console.warn(`[interview-drive] removed admin no longer in the environment: ${account.email}`)
  }
}

let adminSeedPromise: Promise<void> | null = null

/**
 * Ensures the environment-provided admin exists. Runs once per process and is
 * awaited by every admin entry point, so a fresh deployment has a working
 * login without a manual migration step.
 */
export function ensureAdminSeeded(): Promise<void> {
  if (!adminSeedPromise) {
    adminSeedPromise = mutate((db) => {
      seedAdminsFromEnv(db)
    }).catch((error) => {
      adminSeedPromise = null // let a later request retry after a transient failure
      throw error
    })
  }
  return adminSeedPromise
}

/* ---------------------------------------------------------- rate limiting */

/**
 * Fixed-window limiter backed by the same JSON store, so limits survive a
 * restart and apply across processes. Used to blunt credential stuffing.
 */
export async function checkRateLimit(
  key: string,
  limit: number,
  windowMs: number,
): Promise<{ allowed: boolean; remaining: number; retryAfterMs: number }> {
  const now = Date.now()
  return mutate((db) => {
    db.rateLimits = db.rateLimits.filter((hit) => now - hit.at < Math.max(windowMs, 60 * 60 * 1000))
    const hits = db.rateLimits.filter((hit) => hit.key === key && now - hit.at < windowMs)
    if (hits.length >= limit) {
      const oldest = Math.min(...hits.map((h) => h.at))
      return { allowed: false, remaining: 0, retryAfterMs: Math.max(0, windowMs - (now - oldest)) }
    }
    db.rateLimits.push({ key, at: now })
    return { allowed: true, remaining: limit - hits.length - 1, retryAfterMs: 0 }
  })
}

export async function clearRateLimit(key: string): Promise<void> {
  await mutate((db) => {
    db.rateLimits = db.rateLimits.filter((hit) => hit.key !== key)
  })
}

/* -------------------------------------------------------------- sessions */

const hashToken = (token: string) => crypto.createHash("sha256").update(token).digest("hex")

export type LoginResult =
  | { ok: true; token: string; csrfToken: string; admin: AdminUser }
  | { ok: false; reason: "invalid_credentials" }

export async function login(
  email: string,
  password: string,
  meta: { ip?: string | null; userAgent?: string | null } = {},
): Promise<LoginResult> {
  await ensureAdminSeeded()
  const normalized = email.trim().toLowerCase()
  const db = await readDb()
  const admin = db.admins.find((a) => a.email === normalized)

  // Always run a hash comparison so a missing account and a wrong password
  // take indistinguishable time — no user enumeration via response latency.
  const stored = admin?.passwordHash ?? hashPassword(crypto.randomUUID())
  const valid = verifyPassword(password, stored)
  if (!admin || !valid) return { ok: false, reason: "invalid_credentials" }

  const token = crypto.randomBytes(32).toString("base64url")
  const csrfToken = crypto.randomBytes(32).toString("base64url")
  const now = Date.now()

  await mutate((fresh) => {
    const target = fresh.admins.find((a) => a.id === admin.id)
    if (target) target.lastLoginAt = new Date(now).toISOString()
    fresh.sessions = fresh.sessions.filter((s) => Date.parse(s.expiresAt) > now)
    fresh.sessions.push({
      tokenHash: hashToken(token),
      adminId: admin.id,
      csrfToken,
      createdAt: new Date(now).toISOString(),
      expiresAt: new Date(now + SESSION_TTL_MS).toISOString(),
      ip: meta.ip ?? null,
      userAgent: meta.userAgent ?? null,
    })
    appendAdminLog(fresh, {
      adminId: admin.id,
      adminEmail: admin.email,
      action: "admin.login",
      targetType: "admin",
      targetId: admin.id,
      details: null,
      ip: meta.ip ?? null,
    })
  })

  return { ok: true, token, csrfToken, admin }
}

export type AuthenticatedAdmin = { admin: AdminUser; session: AdminSession }

/** Resolves the caller's session, or null. The single gate for admin routes. */
export async function getAuthenticatedAdmin(): Promise<AuthenticatedAdmin | null> {
  const store = await cookies()
  const token = store.get(SESSION_COOKIE)?.value
  if (!token) return null

  await ensureAdminSeeded()
  const db = await readDb()
  const session = db.sessions.find((s) => s.tokenHash === hashToken(token))
  if (!session) return null
  if (Date.parse(session.expiresAt) <= Date.now()) return null

  const admin = db.admins.find((a) => a.id === session.adminId)
  if (!admin) return null
  return { admin, session }
}

export async function logout(): Promise<void> {
  const store = await cookies()
  const token = store.get(SESSION_COOKIE)?.value
  if (token) {
    const tokenHash = hashToken(token)
    await mutate((db) => {
      db.sessions = db.sessions.filter((s) => s.tokenHash !== tokenHash)
    })
  }
  store.delete(SESSION_COOKIE)
}

export function sessionCookieOptions() {
  return {
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "lax" as const,
    path: "/",
    maxAge: SESSION_TTL_MS / 1000,
  }
}

/** Verifies the CSRF token bound to this session for mutating requests. */
export function verifyCsrf(session: AdminSession, headerValue: string | null): boolean {
  if (!headerValue) return false
  const expected = Buffer.from(session.csrfToken)
  const actual = Buffer.from(headerValue)
  if (expected.length !== actual.length) return false
  return crypto.timingSafeEqual(expected, actual)
}
